version: "3.7"

services:
  dmakr:
    build: .
    init: true
    command: nodemon src/index.js

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/app
      - ${PWD}/../mockRepos:/mockRepos
